

name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
   EU_PACKAGE_S3_BUKET_NAME : "cicd-github-actions"
   EU_APPLICATION_NAME      : "Myflask"
   EU_ENVIRONMENT_NAME      : "MyflaskPython-env"
   DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
   AWS_REGION_NAME          : "eu-central-1"
   


on:

  push:
    branches: 
        - master 


jobs:
  my_ci_part:

    runs-on: ubuntu-latest

    steps:
      - name: Git clone our repo
        uses: actions/checkout@v2
        
        

      - name: Create ZIP deploymant package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
        
        
        
        
        
        
        
        
        
        
 
